### ISSUE TITLE
Update Readme with instructions ASAP

### ISSUE THREAD

**Issue by parthasaradhikonda** [tls97nikhila/fruitway#1]
Readme needs to be updated with the following instructions

- Setup instructions PHP, MYSQL and execution instructions.
- Setup instructions if you're using web server like xampp

**Comment by parthasaradhikonda** [comment]
@tls97nikhila please respond ASAP.

**Comment by tls97nikhila** [comment]
Instructions included in Readme file sir.
Thank you
